name: setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: '.dotfiles'
      - name: Install fish
        run: |
          sudo apt-add-repository ppa:fish-shell/release-3
          sudo apt update
          sudo apt install fish
      - name: Run setup.fish
        run: fish setup.fish
