name: setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [go, haskell, node, python, rust]
    steps:
      - uses: actions/checkout@v3
      - name: Set DOT_PATH
        run: echo ${GITHUB_WORKSPACE} > ${GITHUB_WORKSPACE}/.dot_path
      - name: Install fish
        run: |
          sudo apt-add-repository ppa:fish-shell/release-3
          sudo apt update
          sudo apt install fish
      - name: Run setup script
        run: fish setup-${{ matrix.target }}.fish
